# Copyright (c) 2022-2023, AllWorldIT.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.


version: '3.9'

services:

  zabbix-server:
    image: allworldit/zabbix:latest
    hostname: zabbix-server
    environment:
      - ZABBIX_MODE=server
      - ZABBIX_DATABASE_TYPE=timescaledb
      - ZABBIX_ADMIN_USERNAME=Admin
      - ZABBIX_ADMIN_PASSWORD=testtest
      - ZABBIX_SERVER_WEBSERVICE_URL=http://zabbix-webservice:10053/report
      - POSTGRES_HOST=postgresql
      - POSTGRES_DATABASE=zabbix
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=dbpassword
    networks:
      internal:
      external:
        ipv4_address: 172.16.10.10
        ipv6_address: 64:ff9b:1::10:10

  zabbix-frontend:
    image: allworldit/zabbix:latest
    environment:
      ZABBIX_MODE: frontend
      ZABBIX_DATABASE_TYPE: postgresql
      POSTGRES_HOST: postgresql
      POSTGRES_DATABASE: zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: dbpassword
      NGINX_SET_REAL_IP_FROM: |
        172.16.0.0/12
        64:ff9b:1::/96
    ports:
      - '8080:80'
    networks:
      internal:
      external:
        ipv4_address: 172.16.10.20
        ipv6_address: 64:ff9b:1::10:20

  zabbix-webservice:
    image: allworldit/zabbix:latest
    extra_hosts:
      - "zabbix.frontend.example.com:172.16.0.1"
    environment:
      - ZABBIX_MODE=webservice
      - ZABBIX_WEBSERVICE_ALLOWEDIP=zabbix-server
    networks:
      internal:
      external:
        ipv4_address: 172.16.10.30
        ipv6_address: 64:ff9b:1::10:30

  postgresql:
    image: registry.conarx.tech/containers/postgresql-timescaledb
    environment:
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=dbpassword
      - POSTGRES_DATABASE=zabbix
    volumes:
      - './data/postgresql:/var/lib/postgresql/data'
    networks:
      - internal


networks:
  internal:
    driver: bridge
    enable_ipv6: true
    internal: true
  external:
    driver: bridge
    enable_ipv6: true
    driver_opts:
      com.docker.network.bridge.name: docker1
      com.docker.network.enable_ipv6: 'true'
    ipam:
      driver: default
      config:
        - subnet: 172.16.10.0/24
        - subnet: 64:ff9b:1::10:0/112