#!/bin/sh
# Copyright (c) 2022-2025, AllWorldIT.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.


check_tests() {
	service=$1

	i=1800
	while [ "$i" -gt 0 ]; do
		i=$((i-1))

		echo "INFO: Waiting for Zabbix tests to pass [$service]... ${i}s"

		if docker-compose exec "$service" test -e /PASSED_ZABBIX; then
			echo "PASSED:   - Tests passed for $service"
			break
		fi
		sleep 1
	done

	if [ "$i" = 0 ]; then
		echo "FAILED:   - Tests failed for $service"
		return 1
	fi

	return
}



echo "NOTICE: Starting Zabbix tests"

# Run in background so we can see the output
docker-compose up --remove-orphans --renew-anon-volumes --force-recreate &

# This is run within a very minimal environment, we don't have access to using for i in {180..0} or for ((xxxxxx))
TESTS_PASSED=yes
if [ -n "$TESTS_PASSED" ] && ! check_tests zabbix-server; then
	TESTS_PASSED=
fi
if [ -n "$TESTS_PASSED" ] && ! check_tests zabbix-webservice; then
	TESTS_PASSED=
fi


# Encrypted agent via active non-encrypted proxy1a
if [ -n "$TESTS_PASSED" ] && ! check_tests zabbix-proxy1a; then
	TESTS_PASSED=
fi

if [ -n "$TESTS_PASSED" ] && ! check_tests zabbix-test-agent-via-proxy1a-a; then
	TESTS_PASSED=
fi
if [ -n "$TESTS_PASSED" ] && ! check_tests zabbix-test-agent2-via-proxy1a-a; then
	TESTS_PASSED=
fi

if [ -n "$TESTS_PASSED" ] && ! check_tests zabbix-test-agent-via-proxy1a-ae; then
	TESTS_PASSED=
fi
if [ -n "$TESTS_PASSED" ] && ! check_tests zabbix-test-agent2-via-proxy1a-ae; then
	TESTS_PASSED=
fi

if [ -n "$TESTS_PASSED" ] && ! check_tests zabbix-test-agent-via-proxy1a-p; then
	TESTS_PASSED=
fi
if [ -n "$TESTS_PASSED" ] && ! check_tests zabbix-test-agent2-via-proxy1a-p; then
	TESTS_PASSED=
fi

if [ -n "$TESTS_PASSED" ] && ! check_tests zabbix-test-agent-via-proxy1a-pe; then
	TESTS_PASSED=
fi
if [ -n "$TESTS_PASSED" ] && ! check_tests zabbix-test-agent2-via-proxy1a-pe; then
	TESTS_PASSED=
fi

# Encrypted agent via active non-encrypted proxy2ae
if [ -n "$TESTS_PASSED" ] && ! check_tests zabbix-proxy2ae; then
	TESTS_PASSED=
fi

if [ -n "$TESTS_PASSED" ] && ! check_tests zabbix-test-agent-via-proxy2ae-a; then
	TESTS_PASSED=
fi
if [ -n "$TESTS_PASSED" ] && ! check_tests zabbix-test-agent2-via-proxy2ae-a; then
	TESTS_PASSED=
fi

if [ -n "$TESTS_PASSED" ] && ! check_tests zabbix-test-agent-via-proxy2ae-ae; then
	TESTS_PASSED=
fi
if [ -n "$TESTS_PASSED" ] && ! check_tests zabbix-test-agent2-via-proxy2ae-ae; then
	TESTS_PASSED=
fi

if [ -n "$TESTS_PASSED" ] && ! check_tests zabbix-test-agent-via-proxy2ae-p; then
	TESTS_PASSED=
fi
if [ -n "$TESTS_PASSED" ] && ! check_tests zabbix-test-agent2-via-proxy2ae-p; then
	TESTS_PASSED=
fi

if [ -n "$TESTS_PASSED" ] && ! check_tests zabbix-test-agent-via-proxy2ae-pe; then
	TESTS_PASSED=
fi
if [ -n "$TESTS_PASSED" ] && ! check_tests zabbix-test-agent2-via-proxy2ae-pe; then
	TESTS_PASSED=
fi


# Encrypted agent via active non-encrypted proxy3p
if [ -n "$TESTS_PASSED" ] && ! check_tests zabbix-proxy3p; then
	TESTS_PASSED=
fi

if [ -n "$TESTS_PASSED" ] && ! check_tests zabbix-test-agent-via-proxy3p-a; then
	TESTS_PASSED=
fi
if [ -n "$TESTS_PASSED" ] && ! check_tests zabbix-test-agent2-via-proxy3p-a; then
	TESTS_PASSED=
fi

if [ -n "$TESTS_PASSED" ] && ! check_tests zabbix-test-agent-via-proxy3p-ae; then
	TESTS_PASSED=
fi
if [ -n "$TESTS_PASSED" ] && ! check_tests zabbix-test-agent2-via-proxy3p-ae; then
	TESTS_PASSED=
fi

if [ -n "$TESTS_PASSED" ] && ! check_tests zabbix-test-agent-via-proxy3p-p; then
	TESTS_PASSED=
fi
if [ -n "$TESTS_PASSED" ] && ! check_tests zabbix-test-agent2-via-proxy3p-p; then
	TESTS_PASSED=
fi

if [ -n "$TESTS_PASSED" ] && ! check_tests zabbix-test-agent-via-proxy3p-pe; then
	TESTS_PASSED=
fi
if [ -n "$TESTS_PASSED" ] && ! check_tests zabbix-test-agent2-via-proxy3p-pe; then
	TESTS_PASSED=
fi

# Encrypted agent via active non-encrypted proxy4pe
if [ -n "$TESTS_PASSED" ] && ! check_tests zabbix-proxy4pe; then
	TESTS_PASSED=
fi

if [ -n "$TESTS_PASSED" ] && ! check_tests zabbix-test-agent-via-proxy4pe-a; then
	TESTS_PASSED=
fi
if [ -n "$TESTS_PASSED" ] && ! check_tests zabbix-test-agent2-via-proxy4pe-a; then
	TESTS_PASSED=
fi

if [ -n "$TESTS_PASSED" ] && ! check_tests zabbix-test-agent-via-proxy4pe-ae; then
	TESTS_PASSED=
fi
if [ -n "$TESTS_PASSED" ] && ! check_tests zabbix-test-agent2-via-proxy4pe-ae; then
	TESTS_PASSED=
fi

if [ -n "$TESTS_PASSED" ] && ! check_tests zabbix-test-agent-via-proxy4pe-p; then
	TESTS_PASSED=
fi
if [ -n "$TESTS_PASSED" ] && ! check_tests zabbix-test-agent2-via-proxy4pe-p; then
	TESTS_PASSED=
fi

if [ -n "$TESTS_PASSED" ] && ! check_tests zabbix-test-agent-via-proxy4pe-pe; then
	TESTS_PASSED=
fi
if [ -n "$TESTS_PASSED" ] && ! check_tests zabbix-test-agent2-via-proxy4pe-pe; then
	TESTS_PASSED=
fi


if [ -n "$TESTS_PASSED" ] && ! check_tests zabbix-frontend; then
	TESTS_PASSED=
fi


echo "NOTICE: Shutting down Zabbix"
docker-compose down --remove-orphans --volumes


if [ -z "$TESTS_PASSED" ]; then
	echo "ERROR: Zabbix tests failed!"
	exit 1
fi

echo "ALL ZABBIX TESTS PASSED!"
